#!/bin/sh

if [ -z "$*" -o -z "$1" ]; then
  echo "Usage: $0 <basename>"
  exit
fi

BASE="$1"
DIAPATH=`find -name "$BASE".dia`

if [ -z "$DIAPATH" ]; then
  echo "Cannot find $BASE.dia"
  exit 1
fi

DIR=`dirname "$DIAPATH"`
DIR=`basename "$DIR"`

SRC="$DIAPATH"
DST="pics/$DIR/$BASE.png"

echo Converting "$SRC" to "$DST"
dia -n -e "$DST" -t cairo-alpha-png "$SRC"
